# .github/workflows/test.yml
name: Test Solutions

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=. --cov-report=term-missing

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install formatting tools
      run: |
        python -m pip install --upgrade pip
        pip install black flake8
    
    - name: Check code formatting (non-blocking)
      run: |
        # Just show what would be formatted, but don't fail
        black --check --diff . || echo "Code formatting suggestions above"
        # Relaxed linting - only catch serious issues
        flake8 . --max-line-length=88 --ignore=E203,W503,E501 --exclude=tests